apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  #what port in the application is exposed on the port. (ex . nginx runs on port 80)
      nodePort: 30007  # This port can be any valid port within the NodePort range
  type: NodePort